//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Hell0Repo")]
[assembly: AssemblyDescription("Sample")]
[assembly: AssemblyCompany("onovotny")]
[assembly: AssemblyProduct("HelloRepo")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyCopyright("© Oren Novotny 2016")]
[assembly: CLSCompliant(true)]
